---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  namespace: monitoring
  labels:
    team: devops
spec:
  endpoints:
  - port: service
  selector:
    matchLabels:
      app: grafana
